Algoritmo "AtividadePratica5"

Var
// Seção de Declarações das variáveis 
numero1: Real
numero2: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval("Escreva o primeiro número: ")
   Leia(numero1)
   Escreval("Escreva o segundo número: ")
   Leia(numero2)
   Se (numero1 > numero2) Então
      Escreva("O primeiro número é maior!")
   Senão
      Escreva("O segundo número é maior!")
   FimSe

Fimalgoritmo