Algoritmo "AtividadePratica6-letra B"

Var
// Seção de Declarações das variáveis
//Valores das variáveis necessárias para conclusão do solicitado 
i,multiplicacao,num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
//
multiplicacao<-1
ENQUANTO i<=4 FACA
     Escreval("Oi, digite um nº do tipo inteiro: ")
     Leia(num)
     multiplicacao<-multiplicacao*num
     i<-i+1
FIMENQUANTO
       Escreval("Resultado da multiplicação: ", multiplicacao)

Fimalgoritmo
