Algoritmo "TipoDados"

Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
//quando se usa mais de uma linha, colocar l apos escreva - quebra a linha \n
   Escreval("Tipo de Caracteres: Thatiane") //texto - alfanumerico
   Escreval("Tipo de Inteiro: ", 10) //a , concatena o inteiro, ou dado diferentes, entre si
   Escreval("Tipo de Real: ", 10.5)
   Escreval("Tipo de Booleano: ", falso)

Fimalgoritmo