Algoritmo "semnome"

Var
// Seção de Declarações das variáveis e inclusão de int 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Eu gosto de estudar, liteal de tamanho 21")
Escreval("Real positivo com uma casa decimal", 123976.0)
Escreval("Real negativo com 4 casas decimais ", 1.3849)
Escreval("apenas as aspas - liteal de tamanho 1")
Escreval("liteal de tamanho 4: nome")
Escreval("Inteiro", 0)
Escreval("liteal de tamanho 5: @##$%")

Fimalgoritmo
