Algoritmo "semnome"
// Disciplina   : [Criação de aplicações e Sistemas]
// Professor   :  Franklin Portela
// Descrição   : Pseudocodigo que mostra uma frase na tela
// Autor(a)    : Thatiane Rosa Gomes Deboleto
// Data atual  : 04/04/2022
Var
// Seção de Declarações das variáveis 
Escreva("Esta aula foi muito legal, já estou ansiosa pelas proximas!")

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo